### ISSUE TITLE
Inheritance from GraphicsWindow

### ISSUE THREAD

**Issue by eric-reeder** [eric-reeder/24780-project#11]
All of your high level classes (AnimationWindow, UIWindow, PlotWindow) should inherit from the GraphicsWindow class so that I can standardize drawing margins as well as setting position and size.

**Comment by stephaniejennings** [comment]
I posted a revised header file--from my understanding, we just need to inherit the public members from the  Graphics Class? Like don't need any other additional variables or classes?
