### ISSUE TITLE
ODESolver class does not have solve function

### ISSUE THREAD

**Issue by eric-reeder** [eric-reeder/24780-project#13]
The solve function that is called by the DynamicSystemApp class does not exist (or is at least not called "solve").

**Comment by split-tennis-ball** [comment]
I have added the solve function and it only takes the timeStep and the two mass objects as parameters. Just have a look at the function prototype. Also, the solver object has some initializing functions which will have to be called from the initializeApp() function with the appropriate parameters.

**Comment by eric-reeder** [comment]
Ok, I'll modify the inputs to the solve function in the DynamicSystemApp class and work on getting the initialization function set up. I'll let you know if I have any questions about that.

**Comment by eric-reeder** [comment]
All right, I think it should be set up all right now. Take a look and if it seems good to you then feel free to close the issue.

**Comment by split-tennis-ball** [comment]
Yes, it looks good to me.
